[package]
name = "mongodb-whiteboard"
version = "0.1.0"
edition = "2021"

[dependencies]
socketioxide-mongodb = { path = "../../crates/socketioxide-mongodb" }
socketioxide = { workspace = true, features = ["tracing", "msgpack"] }
axum.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tower-http.workspace = true
tower.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
serde.workspace = true
rmpv.workspace = true

[[bin]]
name = "mongodb"
path = "src/mongodb.rs"

[[bin]]
name = "mongodb-capped"
path = "src/mongodb_capped.rs"
